[package]
name = "rustreexo"
version = "0.4.0"
edition = "2021"
description = "Utreexo accumulator library"
license = "MIT"

[dependencies]
bitcoin_hashes = "0.14"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
rayon = "1.7"

[lib]
name = "rustreexo"
path = "lib.rs"

[features]
default = []
with-serde = ["serde"]
bench = []